### PR TITLE
Refinement of the recent barrel recipe changes

### PR DESCRIPTION
**Pull request by FantasyTeddy**
I did some more changes to the barrel recipe part which also include the possibility to click on the fluids within the barrel recipe interface to access its 'usages' and 'recipes'.

### CODE REVIEW

**Comment by dries007** [comment]
Nice work! Again xd

**Comment by FantasyTeddy** [comment]
Thanks =)
I hope you don't mind me combing through your code like this...
Btw. another PR is almost ready xP

**Comment by dries007** [comment]
This is why the mod is open source

**Comment by FantasyTeddy** [comment]
Perfect!
Btw if I never mentioned it: I really love this plugin, which is the reason I'm trying to help improving it wherever possible ;)

**Pull request merged**
